[build]
  publish = "/"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@supabase/supabase-js", "googleapis"]

[dev]
  framework = "#static"
  targetPort = 3000 